# Generated by Django 6.0.7 on 2026-07-09 11:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin (Site Sahibi)'), ('SELLER', 'Seller (Satıcı Mağaza)'), ('CUSTOMER', 'Customer (Müşteri)')], default='CUSTOMER', help_text='Kullanıcının platformdaki yetki rolü.', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Ödeme Bekleniyor'), ('PAID', 'Ödendi'), ('FAILED', 'Ödeme Başarısız')], default='PENDING', max_length=20, verbose_name='Ödeme Durumu')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ödeme Gateway ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ürün Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Ürün Açıklaması')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taban Fiyat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.category', verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Renk')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Beden')),
                ('size_number', models.IntegerField(blank=True, null=True, verbose_name='Numara')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Boş bırakılırsa ürünün taban fiyatı (base_price) geçerli olur.', max_digits=10, null=True, verbose_name='Varyasyon Fiyatı')),
                ('stock', models.IntegerField(default=0, verbose_name='Stok Adedi')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Stok Kodu (SKU)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='marketplace.product', verbose_name='Ürün')),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=150, unique=True, verbose_name='Mağaza Adı')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN Numarası (Simülasyon için)')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Platformun bu satıcının satışlarından alacağı komisyon yüzdesi (örn: 10.00)', max_digits=5, verbose_name='Komisyon Oranı (%)')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Onay Durumu')),
                ('user', models.OneToOneField(help_text="Her profil bir CustomUser'a bağlıdır (ASP.NET'teki [Required] veya FK ilişkisi).", on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.sellerprofile', verbose_name='Satıcı (Mağaza)'),
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satıcı Ara Toplam')),
                ('commission_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Platform Komisyon Kesintisi (Simüle Edilen)')),
                ('seller_payout', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satıcıya Aktarılacak Tutar (Net Hak Ediş)')),
                ('status', models.CharField(choices=[('PENDING', 'Hazırlanıyor'), ('SHIPPED', 'Kargoya Verildi'), ('DELIVERED', 'Teslim Edildi'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=20, verbose_name='Sipariş Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='marketplace.order', verbose_name='Ana Sipariş')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='marketplace.sellerprofile', verbose_name='Satıcı')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Satış Fiyatı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.product', verbose_name='Ürün')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.productvariant', verbose_name='Ürün Varyasyonu')),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.suborder', verbose_name='Alt Sipariş')),
            ],
        ),
    ]
