# Generated by Django 6.0.4 on 2026-07-15 09:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kupon Kodu')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Yüzdelik'), ('FIXED_AMOUNT', 'Sabit Tutar')], default='PERCENTAGE', max_length=20, verbose_name='İndirim Tipi')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İndirim Değeri')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Minimum Sepet Tutarı')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='Kullanım Limiti')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Kullanım Sayısı')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Son Kullanma Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
