# Generated by Django 6.0.4 on 2026-07-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_product_average_rating_product_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tahmini Teslimat Tarihi'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('RECEIVED', 'Alındı'), ('PREPARING', 'Hazırlanıyor'), ('SHIPPED', 'Kargoya Verildi'), ('DELIVERED', 'Teslim Edildi'), ('CANCELLED', 'İptal')], default='RECEIVED', max_length=20, verbose_name='Sipariş Durumu'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kargo Firması'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kargo Takip Numarası'),
        ),
    ]
