# Generated by Django 6.0.7 on 2026-07-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_order_estimated_delivery_date_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Yorum Görseli'),
        ),
    ]
