# Generated by Django 6.0.7 on 2026-07-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_productreview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='marketplace.sellerprofile', verbose_name='Satıcı Mağaza'),
        ),
    ]
