# Generated by Django 6.0.4 on 2026-07-23 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_pushdevicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Flaş İndirim Oranı (%)')),
                ('end_time', models.DateTimeField(verbose_name='Kampanya Bitiş Zamanı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kampanya Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale', to='marketplace.product')),
            ],
        ),
    ]
