# Generated by Django 6.0.4 on 2026-07-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_rewardtransaction_userrewardpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Faydalı Bulma Sayısı'),
        ),
    ]
