# Generated by Django 6.0.4 on 2026-07-27 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_productreview_helpful_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondHandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='İlan Başlığı')),
                ('description', models.TextField(verbose_name='İlan Açıklaması')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('condition', models.CharField(choices=[('NEW_LIKE', 'Sıfır Gibi (Etiketli)'), ('GOOD', 'Az Kullanılmış (Temiz)'), ('FAIR', 'Kullanılmış (Makul)')], default='GOOD', max_length=20, verbose_name='Ürün Durumu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='second_hand/', verbose_name='İlan Görseli')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Satıldı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_hand_items', to=settings.AUTH_USER_MODEL, verbose_name='Satıcı Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Teklif Edilen Fiyat')),
                ('status', models.CharField(choices=[('PENDING', 'Yanıt Bekliyor'), ('ACCEPTED', 'Kabul Edildi'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=20, verbose_name='Teklif Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_offers', to=settings.AUTH_USER_MODEL, verbose_name='Teklif Veren Alıcı')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.product', verbose_name='Sıfır Ürün')),
                ('second_hand_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.secondhanditem', verbose_name='İkinci El İlan')),
            ],
        ),
    ]
