# Generated by Django 6.0.4 on 2026-07-28 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_secondhanditem_productoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Adres Başlığı (Ev, İş vb.)')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('city', models.CharField(max_length=50, verbose_name='İl')),
                ('district', models.CharField(max_length=50, verbose_name='İlçe')),
                ('address_text', models.TextField(verbose_name='Açık Adres')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Adres mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
