# Generated by Django 6.0.4 on 2026-08-01 09:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=150, unique=True, verbose_name='Arama Kelimesi')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Aranma Sayısı')),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-count', '-last_searched_at'],
            },
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Müşteri'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='İade Edilecek Tutar'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='return_shipping_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İade Kargo Kodu'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='sub_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='marketplace.suborder', verbose_name='Alt Sipariş'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='marketplace.orderitem'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Onay Bekliyor'), ('APPROVED', 'Onaylandı (İade Alındı)'), ('REJECTED', 'İade Reddedildi'), ('COMPLETED', 'Tamamlandı (Ücret İade Edildi)')], default='PENDING', max_length=20, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField(verbose_name='Değişim Miktarı (+ / -)')),
                ('previous_stock', models.IntegerField(verbose_name='Önceki Stok')),
                ('new_stock', models.IntegerField(verbose_name='Yeni Stok')),
                ('reason', models.CharField(max_length=200, verbose_name='Değişim Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='marketplace.productvariant', verbose_name='Ürün Varyasyonu')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cüzdan Bakiyesi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Para Girişi (Kredi)'), ('DEBIT', 'Para Çıkışı (Harcama)')], max_length=10, verbose_name='İşlem Tipi')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace.wallet')),
            ],
        ),
    ]
