# Generated by Django 6.0.4 on 2026-08-01 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_searchquerylog_returnrequest_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='PazarPuan')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Toplam Harcama')),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronz Üye'), ('SILVER', 'Gümüş Üye'), ('GOLD', 'Altın Üye'), ('PLATINUM', 'Platin VIP Üye')], default='BRONZE', max_length=20, verbose_name='Üyelik Seviyesi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
