# Generated by Django 6.0.7 on 2026-08-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_userloyalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_palette',
            field=models.JSONField(blank=True, default=list, verbose_name='Baskın Renk Paleti'),
        ),
        migrations.AddField(
            model_name='product',
            name='dominant_color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Baskın Renk Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='lqip_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Blur-Up (LQIP) Base64'),
        ),
        migrations.AddField(
            model_name='product',
            name='responsive_images',
            field=models.JSONField(blank=True, default=dict, verbose_name='Responsive Görsel Varyantları'),
        ),
    ]
